Create
AsBuiltReport/AsBuiltReport.VMware.UAG pull request #1
Opened 2019-12-29 22:51 UTC by childebrandt42

2020-01-18 02:39 UTC, childebrandt42 commented
Final

2020-01-18 02:41 UTC, childebrandt42 commented
Final

2020-02-19 05:49 UTC, tpcarman requested changes

2020-02-19 05:49 UTC, tpcarman commented on .vscode/settings.json
> +    "powershell.bugReporting.project": "https://github.com/tpcarman/As-Built-Report/",
`"powershell.bugReporting.project": "https://github.com/AsBuiltReport/AsBuiltReport.VMware.UAG/"`

2020-02-19 05:49 UTC, tpcarman commented on .vscode/launch.json
> +{
File not required, please remove

2020-02-19 05:49 UTC, tpcarman commented on AsBuiltReport.VMware.UAG.Style.ps1
> +        'Date:' = Get-Date -Format 'dd MMMM yyyy'
`'Date:' = (Get-Date).ToLongDateString()`

2020-02-19 05:49 UTC, tpcarman commented on README.md
> +
Include `## Supported UAG Versions`

2020-02-19 05:49 UTC, tpcarman commented on README.md
> +Install-Module AsBuiltReport
```powershell
install-module AsBuiltReport.VMware.UAG
```

2020-02-19 05:49 UTC, tpcarman commented on README.md
> +The UAG Management port is required to have a trusted cert installed. If there is no trusted cert it will error. Workaround is to install a trusted cert or add the cert to the trusted certs store on
Workaround is to install a trusted cert or add the cert to the trusted certs store on the machine running the VMware UAG (Universial Access Gateway) As Built Report.

2020-07-06 23:59 UTC, tpcarman approved these changes

2020-07-06 23:59 UTC, merged